local _, rDL = ...

local phrases = {
	"Haha, Robin, n00b!",
	"Kanske borde träna lite mer, Robin?",
	"Bra försök, Robin!",
	"Är det allt du kan, Robin?",
	"Robin, du behöver mer övning!",
	"När ska du sluta dö, Robin?",
	"Robin, det var pinsamt!",
	"Kanske nästa gång, Robin!",
	"Du är inte så bra, Robin!",
	"Robin, du får bättre kritik i dödschatten!",
	"Hån, hån, hån, Robin!",
	"Inte imponerad, Robin.",
	"Är det allt du har, Robin?",
	"Robin, det var så enkelt!",
	"Du kan göra bättre än så, Robin!",
	"Robin, du är som en skugga av en spelare.",
	"Lätt som en plätt, Robin!",
	"Kanske borde byta karaktär, Robin?",
	"Robin, du gör det så svårt att håna dig!",
	"Bättre lycka nästa gång, Robin.",
	"Det där såg ut som en Robin-död, eller hur?",
	"Robin, du är verkligen en utmaning...",
	"Robin, är du fortfarande med oss?",
	"Hoppas att du blir bättre, Robin!",
	"Robin, du får mig att skratta!",
	"Det var inte ens en match, Robin!",
	"Robin, vi kanske borde göra en insamling för dig?",
	"Bättre tur nästa gång, Robin!",
	"Robin, du gör mig stolt!",
	"Haha, Robin, bättre lycka nästa gång!",
	"Robin, det där var komiskt!",
	"Det är okej, Robin, vi alla dör ibland.",
	"Robin, det är bara ett spel, oroa dig inte!",
	"Inte förvånad, Robin.",
	"Robin, det var som att skjuta fisk i en tunna!",
	"Hånar Robin är som att hånar en gräsmatta.",
	"Robin, du förtjänar en medalj för ditt döende!",
	"Död igen, Robin? Ingen överraskning där!",
	"Bättre kuckeliku nästa gång, Robin!",
	"Robin, du gör mitt spel så underhållande!",
	"Robin, du är som en förlorare, fast värre!",
	"Det var nästan tråkigt, Robin.",
	"Kanske borde sluta spela, Robin?",
	"Robin, du är verkligen speciell!",
	"Robin, du är en konstnär av att dö!",
	"Det där var som musik i mina öron, Robin.",
	"Robin, du ger färg åt mitt spel!",
	"Ingen match, Robin!",
	"Robin, är du ens på riktigt?",
	"Är det verkligen du, Robin?",
	"Robin, du är min hjälte!",
	"Kanske kan jag lära dig spela, Robin?",
	"Robin, du är som en legend i döende!",
	"Det är verkligen en konst att vara så dålig, Robin.",
	"Robin, jag är förundrad över din brist på skicklighet!",
	"Haha, Robin, du får mig att skratta varje gång!",
	"Robin, du kan inte vara på riktigt...",
	"Robin, om det här var en tävling skulle du förlora!",
	"Bättre lycka nästa död, Robin!",
	"Hoppas att du inte blir för ledsen, Robin!",
	"Robin, du förtjänar en plats i historieböckerna!",
	"Du är som en komisk figur, Robin!",
	"Robin, du gör mig alltid på gott humör!",
	"Robin, varje gång du dör blir världen lite ljusare!",
	"Det är svårt att inte skratta åt dig, Robin.",
	"Robin, du är som en gåva till mitt spel!",
	"Inte ens nära att vara bra, Robin!",
	"Robin, du är en mästare av döden!",
	"Bättre att dö än att vara dålig, eller hur, Robin?",
	"Robin, du är som en legendarisk förlorare!",
	"Din död är alltid en höjdpunkt, Robin!",
	"Robin, du är som en komisk karaktär!",
	"Det är svårt att inte älska dig, Robin.",
	"Robin, du är som en levande meme!",
	"Haha, Robin, du förtjänar en medalj!",
	"Robin, du får mig alltid att skratta högt!",
	"Det är som att se en upprepning varje gång, Robin.",
	"Bättre lycka nästa gång du dör, Robin!",
	"Robin, du är som en gåva till gaming-världen!",
	"Din död är som ett konstverk, Robin!",
	"Robin, du är som en bok som jag inte kan sluta läsa!",
	"Det var som att se en film, Robin!",
	"Robin, du är som en legendarisk förlorare!",
	"Robin, din död är som en fyrverkerishow!",
	"Det var som att se en liveföreställning, Robin!",
	"Bättre död än dålig, eller hur, Robin?",
	"Robin, du är som en glädjespridare i spelet!",
	"Haha, Robin, du är min favoritförlorare!",
	"Robin, du får mig alltid att vilja spela mer!",
	"Din död är som musik i mina öron, Robin!",
	"Robin, du är som en levande skämt!",
	"Det är som att se en komedi varje gång, Robin.",
	"Bättre än tv, Robin!",
	"Robin, du är som en skatt i gaming-världen!",
	"Robin, jag skulle betala för att se dig dö igen!",
	"Din död är som en solnedgång, Robin!",
	"Robin, du förtjänar en speciell plats i mitt hjärta!",
	"Det är som att se en föreställning varje gång, Robin.",
	"Bättre än en sitcom, Robin!",
	"Robin, du är som en förlorares förlorare!",
	"Robin, du är som en dödsstjärna i gaming!",
	"Din död är som en fyrverkerishow i spelet, Robin!",
}

function rDL:getRandomPhrase()
	return phrases[math.random(1, #phrases)]
end
